# Generated by Django 4.0 on 2021-12-28 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_cart_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='count',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='sub_category',
        ),
        migrations.AddField(
            model_name='cart',
            name='product',
            field=models.CharField(blank=True, max_length=10000, null=True),
        ),
    ]
