# Generated by Django 4.0 on 2022-01-06 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_text'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Text',
            new_name='Texts',
        ),
    ]
