# Generated by Django 4.0 on 2022-01-07 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_userstype'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstype',
            name='phone',
            field=models.CharField(default='', max_length=13),
            preserve_default=False,
        ),
    ]
