# Generated by Django 4.0 on 2022-01-07 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_userstype_accesses'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdsModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[(1, 'Barcha'), (2, 'Uz'), (3, 'Ru')], max_length=100)),
                ('file', models.FileField(upload_to='images/')),
                ('message', models.TextField()),
            ],
        ),
    ]
