# Generated by Django 4.0 on 2022-01-07 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0016_alter_adsmodel_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adsmodel',
            name='status',
            field=models.CharField(choices=[('all', 'Barcha'), ('uz', 'Uz'), ('ru', 'Ru')], max_length=255),
        ),
    ]
