# Generated by Django 4.0 on 2022-01-07 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_alter_adsmodel_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='adsmodel',
            name='send_status',
            field=models.BooleanField(default=False),
        ),
    ]
