# Generated by Django 4.0 on 2022-01-08 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_adsmodel_send_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adsmodel',
            name='send_status',
        ),
    ]
