# Generated by Django 4.0 on 2022-01-08 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0020_adsmodel_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adsmodel',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
