# Generated by Django 4.0 on 2022-01-08 05:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_adsmodel_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adsmodel',
            name='file',
            field=models.FileField(upload_to='images/', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'jpg', 'png', 'jpeg', 'avi', 'mov'])]),
        ),
    ]
