# Generated by Django 4.0 on 2022-01-08 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0023_alter_adsmodel_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(default='5075005699:AAGOOqqI25wpSa6MW9FhxISC2zHSmzOGvlI', max_length=255)),
                ('deliver_time_from', models.TimeField()),
                ('deliver_time_to', models.TimeField()),
            ],
        ),
    ]
