# Generated by Django 4.0 on 2022-01-08 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0025_userstype_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userstype',
            old_name='status',
            new_name='active',
        ),
    ]
