# Generated by Django 4.0 on 2022-01-09 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0029_rename_cart_order_carts'),
    ]

    operations = [
        migrations.AddField(
            model_name='botsettings',
            name='group_id',
            field=models.CharField(default=1, max_length=30),
        ),
    ]
