# Generated by Django 4.0 on 2022-01-10 16:48

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0030_botsettings_group_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstype',
            name='accesses',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('cashier', 'Кассир'), ('order', 'Zakaz'), ('menu', 'Menu'), ('statistic', 'Statistika'), ('Ad', 'Ad'), ('fillial', 'Fillial'), ('users', 'Users'), ('followers', 'Followers'), ('settings_bot', 'Bot Settings'), ('settings_bot', 'Bot Settings')], max_length=81),
        ),
    ]
