# Generated by Django 4.0 on 2022-01-10 18:19

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0031_alter_userstype_accesses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userstype',
            name='accesses',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('cashier', 'Кассир'), ('order', 'Заказ'), ('menu', 'Меню'), ('statistic', 'Статистика'), ('map', 'Карта'), ('Ad', 'Рассылки'), ('fillial', 'Филиалы'), ('users', 'Пользователи'), ('followers', 'Подписчики'), ('settings_bot', 'Настройки бота')], max_length=72),
        ),
        migrations.AlterField(
            model_name='userstype',
            name='type',
            field=models.CharField(choices=[('admin', 'Администратор'), ('manager', 'Менеджер'), ('kassir', 'Кассир')], max_length=200),
        ),
    ]
