# Generated by Django 4.0 on 2022-01-10 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0032_alter_userstype_accesses_alter_userstype_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adsmodel',
            name='status',
            field=models.CharField(choices=[('all', 'Все'), ('uz', 'Uz'), ('ru', 'Ru')], max_length=255),
        ),
    ]
