# Generated by Django 4.0 on 2022-01-10 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0033_alter_adsmodel_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botsettings',
            name='token',
            field=models.CharField(default='5075005699:AAGGFW7NCbRq-TvflzsECUfU6ZzzGDFpLXU', max_length=255),
        ),
    ]
