# Generated by Django 4.0 on 2022-01-11 18:08

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0034_alter_botsettings_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey( on_delete=django.db.models.deletion.CASCADE, to='myapp.costumers'),
            preserve_default=False,
        ),
    ]
