# Generated by Django 4.0 on 2022-01-11 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0035_order_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='botsettings',
            name='deliver_km',
            field=models.CharField(default=10, max_length=3),
        ),
    ]
