# Generated by Django 4.0 on 2022-01-15 15:23

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0037_category_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adsmodel',
            name='message',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
