# Generated by Django 4.0 on 2022-01-15 17:28

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0038_alter_adsmodel_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='texts',
            name='ru_text',
            field=ckeditor.fields.RichTextField(),
        ),
        migrations.AlterField(
            model_name='texts',
            name='uz_text',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
