# Generated by Django 4.0 on 2022-01-17 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0039_alter_texts_ru_text_alter_texts_uz_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='botsettings',
            name='click',
            field=models.CharField(default='1', max_length=255),
        ),
        migrations.AddField(
            model_name='botsettings',
            name='payme',
            field=models.CharField(default='1', max_length=255),
        ),
    ]
