# Generated by Django 4.0 on 2022-01-18 09:57

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0041_subcategory_desc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcategory',
            name='desc',
        ),
        migrations.AddField(
            model_name='category',
            name='desc',
            field=ckeditor.fields.RichTextField(default=''),
            preserve_default=False,
        ),
    ]
