# Generated by Django 4.0 on 2022-01-24 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0042_remove_subcategory_desc_category_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='deliver_time',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
