# Generated by Django 4.0 on 2022-01-24 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0044_comments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='file',
            field=models.URLField(null=True),
        ),
    ]
