# Generated by Django 4.0 on 2022-01-25 09:47

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0047_alter_userstype_accesses'),
    ]

    operations = [
        migrations.AddField(
            model_name='subcategory',
            name='desc',
            field=ckeditor.fields.RichTextField(default=''),
            preserve_default=False,
        ),
    ]
