# Generated by Django 4.0 on 2022-01-26 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0048_subcategory_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='com_type',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
