# Generated by Django 4.0 on 2022-02-03 15:47

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0049_comments_com_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='desc',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='desc',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
